/* example.c generated by valac 0.16.1, the Vala compiler
 * generated from example.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gtkwidgetexample.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
typedef struct _MainWindowPrivate MainWindowPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

struct _MainWindow {
	GtkWindow parent_instance;
	MainWindowPrivate * priv;
};

struct _MainWindowClass {
	GtkWindowClass parent_class;
};

struct _Main {
	GObject parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GObjectClass parent_class;
};


static gpointer main_window_parent_class = NULL;
static gpointer main_parent_class = NULL;

GType main_window_get_type (void) G_GNUC_CONST;
enum  {
	MAIN_WINDOW_DUMMY_PROPERTY
};
MainWindow* main_window_new (void);
MainWindow* main_window_construct (GType object_type);
GType main_get_type (void) G_GNUC_CONST;
enum  {
	MAIN_DUMMY_PROPERTY
};
gint main_main (gchar** args, int args_length1);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
Main* main_new (void);
Main* main_construct (GType object_type);


MainWindow* main_window_construct (GType object_type) {
	MainWindow * self = NULL;
	GtkWidgetExampleWidget* _tmp0_;
	GtkWidgetExampleWidget* _tmp1_;
	GtkWidgetExampleWidget* widget;
#line 4 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	self = (MainWindow*) g_object_new (object_type, NULL);
#line 6 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	_tmp0_ = gtk_widget_example_widget_new ();
#line 6 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	_tmp1_ = g_object_ref_sink (_tmp0_);
#line 6 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	widget = _tmp1_;
#line 7 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) widget);
#line 4 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	_g_object_unref0 (widget);
#line 4 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	return self;
#line 94 "example.c"
}


MainWindow* main_window_new (void) {
#line 4 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	return main_window_construct (TYPE_MAIN_WINDOW);
#line 101 "example.c"
}


static void main_window_class_init (MainWindowClass * klass) {
#line 1 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	main_window_parent_class = g_type_class_peek_parent (klass);
#line 108 "example.c"
}


static void main_window_instance_init (MainWindow * self) {
}


GType main_window_get_type (void) {
	static volatile gsize main_window_type_id__volatile = 0;
	if (g_once_init_enter (&main_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MainWindow), 0, (GInstanceInitFunc) main_window_instance_init, NULL };
		GType main_window_type_id;
		main_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "MainWindow", &g_define_type_info, 0);
		g_once_init_leave (&main_window_type_id__volatile, main_window_type_id);
	}
	return main_window_type_id__volatile;
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	gtk_main_quit ();
#line 131 "example.c"
}


gint main_main (gchar** args, int args_length1) {
	gint result = 0;
	MainWindow* _tmp0_;
	MainWindow* _tmp1_;
	MainWindow* mainwindow;
#line 14 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	gtk_init (&args_length1, &args);
#line 16 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	_tmp0_ = main_window_new ();
#line 16 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	_tmp1_ = g_object_ref_sink (_tmp0_);
#line 16 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	mainwindow = _tmp1_;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	g_signal_connect ((GtkWidget*) mainwindow, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
#line 18 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	gtk_widget_show_all ((GtkWidget*) mainwindow);
#line 20 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	gtk_main ();
#line 21 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	result = 0;
#line 21 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	_g_object_unref0 (mainwindow);
#line 21 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	return result;
#line 160 "example.c"
}


int main (int argc, char ** argv) {
#line 13 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	g_type_init ();
#line 13 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	return main_main (argv, argc);
#line 169 "example.c"
}


Main* main_construct (GType object_type) {
	Main * self = NULL;
#line 11 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	self = (Main*) g_object_new (object_type, NULL);
#line 11 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	return self;
#line 179 "example.c"
}


Main* main_new (void) {
#line 11 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	return main_construct (TYPE_MAIN);
#line 186 "example.c"
}


static void main_class_init (MainClass * klass) {
#line 11 "/home/luiz/projects/GtkWidgetExampleVala/src/example.vala"
	main_parent_class = g_type_class_peek_parent (klass);
#line 193 "example.c"
}


static void main_instance_init (Main * self) {
}


GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (G_TYPE_OBJECT, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}



