/* GtkWidgetExample-3.0.vapi generated by valac-0.16 0.16.1, do not modify. */

namespace GtkWidgetExample {
	[CCode (cheader_filename = "gtkwidgetexample.h")]
	public class Widget : Gtk.Grid {
		public Widget ();
		public override void size_allocate (Gtk.Allocation allocation);
	}
}
