/* gtkwidgetexample.h generated by valac 0.16.1, the Vala compiler, do not modify */


#ifndef __GTKWIDGETEXAMPLE_H__
#define __GTKWIDGETEXAMPLE_H__

#include <glib.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS


#define GTK_WIDGET_EXAMPLE_TYPE_WIDGET (gtk_widget_example_widget_get_type ())
#define GTK_WIDGET_EXAMPLE_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_WIDGET_EXAMPLE_TYPE_WIDGET, GtkWidgetExampleWidget))
#define GTK_WIDGET_EXAMPLE_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTK_WIDGET_EXAMPLE_TYPE_WIDGET, GtkWidgetExampleWidgetClass))
#define GTK_WIDGET_EXAMPLE_IS_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTK_WIDGET_EXAMPLE_TYPE_WIDGET))
#define GTK_WIDGET_EXAMPLE_IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTK_WIDGET_EXAMPLE_TYPE_WIDGET))
#define GTK_WIDGET_EXAMPLE_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTK_WIDGET_EXAMPLE_TYPE_WIDGET, GtkWidgetExampleWidgetClass))

typedef struct _GtkWidgetExampleWidget GtkWidgetExampleWidget;
typedef struct _GtkWidgetExampleWidgetClass GtkWidgetExampleWidgetClass;
typedef struct _GtkWidgetExampleWidgetPrivate GtkWidgetExampleWidgetPrivate;

struct _GtkWidgetExampleWidget {
	GtkGrid parent_instance;
	GtkWidgetExampleWidgetPrivate * priv;
};

struct _GtkWidgetExampleWidgetClass {
	GtkGridClass parent_class;
};


GType gtk_widget_example_widget_get_type (void) G_GNUC_CONST;
GtkWidgetExampleWidget* gtk_widget_example_widget_new (void);
GtkWidgetExampleWidget* gtk_widget_example_widget_construct (GType object_type);


G_END_DECLS

#endif
