/* gtkwidgetexample.c generated by valac 0.16.1, the Vala compiler
 * generated from gtkwidgetexample.vala, do not modify */

/* gtkwidgetexample.vala
 *
 * Copyright (C) 2012 Luiz Armesto <luiz.armesto@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version. See http://www.gnu.org/copyleft/gpl.html the full text of the
 * license.
 *
 * Author:
 *	  Luiz Armesto <luiz.armesto@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <pango/pango.h>
#include <gdk/gdk.h>
#include <string.h>
#include <cairo.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <pango/pangocairo.h>


#define GTK_WIDGET_EXAMPLE_TYPE_WIDGET_BASE (gtk_widget_example_widget_base_get_type ())
#define GTK_WIDGET_EXAMPLE_WIDGET_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_WIDGET_EXAMPLE_TYPE_WIDGET_BASE, GtkWidgetExampleWidgetBase))
#define GTK_WIDGET_EXAMPLE_WIDGET_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTK_WIDGET_EXAMPLE_TYPE_WIDGET_BASE, GtkWidgetExampleWidgetBaseClass))
#define GTK_WIDGET_EXAMPLE_IS_WIDGET_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTK_WIDGET_EXAMPLE_TYPE_WIDGET_BASE))
#define GTK_WIDGET_EXAMPLE_IS_WIDGET_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTK_WIDGET_EXAMPLE_TYPE_WIDGET_BASE))
#define GTK_WIDGET_EXAMPLE_WIDGET_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTK_WIDGET_EXAMPLE_TYPE_WIDGET_BASE, GtkWidgetExampleWidgetBaseClass))

typedef struct _GtkWidgetExampleWidgetBase GtkWidgetExampleWidgetBase;
typedef struct _GtkWidgetExampleWidgetBaseClass GtkWidgetExampleWidgetBaseClass;
typedef struct _GtkWidgetExampleWidgetBasePrivate GtkWidgetExampleWidgetBasePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _cairo_region_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_region_destroy (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define GTK_WIDGET_EXAMPLE_TYPE_WIDGET (gtk_widget_example_widget_get_type ())
#define GTK_WIDGET_EXAMPLE_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_WIDGET_EXAMPLE_TYPE_WIDGET, GtkWidgetExampleWidget))
#define GTK_WIDGET_EXAMPLE_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTK_WIDGET_EXAMPLE_TYPE_WIDGET, GtkWidgetExampleWidgetClass))
#define GTK_WIDGET_EXAMPLE_IS_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTK_WIDGET_EXAMPLE_TYPE_WIDGET))
#define GTK_WIDGET_EXAMPLE_IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTK_WIDGET_EXAMPLE_TYPE_WIDGET))
#define GTK_WIDGET_EXAMPLE_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTK_WIDGET_EXAMPLE_TYPE_WIDGET, GtkWidgetExampleWidgetClass))

typedef struct _GtkWidgetExampleWidget GtkWidgetExampleWidget;
typedef struct _GtkWidgetExampleWidgetClass GtkWidgetExampleWidgetClass;
typedef struct _GtkWidgetExampleWidgetPrivate GtkWidgetExampleWidgetPrivate;

struct _GtkWidgetExampleWidgetBase {
	GtkWidget parent_instance;
	GtkWidgetExampleWidgetBasePrivate * priv;
};

struct _GtkWidgetExampleWidgetBaseClass {
	GtkWidgetClass parent_class;
};

struct _GtkWidgetExampleWidgetBasePrivate {
	gboolean dragging;
	GtkCssProvider* css_provider;
	PangoLayout* layout;
	gint step;
	gint pos;
	gint margin_size;
	GDateTime* today;
};

struct _GtkWidgetExampleWidget {
	GtkGrid parent_instance;
	GtkWidgetExampleWidgetPrivate * priv;
};

struct _GtkWidgetExampleWidgetClass {
	GtkGridClass parent_class;
};

struct _GtkWidgetExampleWidgetPrivate {
	gint width;
	gint height;
	GtkWidgetExampleWidgetBase* widget;
	GtkButton* lbutton;
	GtkButton* rbutton;
};


static gpointer gtk_widget_example_widget_base_parent_class = NULL;
static gpointer gtk_widget_example_widget_parent_class = NULL;

GType gtk_widget_example_widget_base_get_type (void) G_GNUC_CONST;
#define GTK_WIDGET_EXAMPLE_WIDGET_BASE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GTK_WIDGET_EXAMPLE_TYPE_WIDGET_BASE, GtkWidgetExampleWidgetBasePrivate))
enum  {
	GTK_WIDGET_EXAMPLE_WIDGET_BASE_DUMMY_PROPERTY
};
GtkWidgetExampleWidgetBase* gtk_widget_example_widget_base_new (void);
GtkWidgetExampleWidgetBase* gtk_widget_example_widget_base_construct (GType object_type);
static void gtk_widget_example_widget_base_real_size_allocate (GtkWidget* base, GtkAllocation* allocation);
static void gtk_widget_example_widget_base_real_realize (GtkWidget* base);
static void gtk_widget_example_widget_base_real_unrealize (GtkWidget* base);
static void gtk_widget_example_widget_base_real_get_preferred_width (GtkWidget* base, gint* minimum_width, gint* natural_width);
static void gtk_widget_example_widget_base_real_get_preferred_width_for_height (GtkWidget* base, gint height, gint* minimum_width, gint* natural_width);
static void gtk_widget_example_widget_base_real_get_preferred_height (GtkWidget* base, gint* minimum_height, gint* natural_height);
static void gtk_widget_example_widget_base_real_get_preferred_height_for_width (GtkWidget* base, gint width, gint* minimum_height, gint* natural_height);
static gboolean gtk_widget_example_widget_base_real_draw (GtkWidget* base, cairo_t* cr);
static gboolean gtk_widget_example_widget_base_real_button_press_event (GtkWidget* base, GdkEventButton* event);
static gboolean gtk_widget_example_widget_base_real_button_release_event (GtkWidget* base, GdkEventButton* event);
static void gtk_widget_example_widget_base_emit_changed_signal (GtkWidgetExampleWidgetBase* self);
static gboolean gtk_widget_example_widget_base_real_motion_notify_event (GtkWidget* base, GdkEventMotion* event);
static void gtk_widget_example_widget_base_redraw_canvas (GtkWidgetExampleWidgetBase* self);
void gtk_widget_example_widget_base_scroll_left (GtkWidgetExampleWidgetBase* self);
static void gtk_widget_example_widget_base_scroll (GtkWidgetExampleWidgetBase* self, gint step);
void gtk_widget_example_widget_base_scroll_right (GtkWidgetExampleWidgetBase* self);
static GObject * gtk_widget_example_widget_base_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void gtk_widget_example_widget_base_finalize (GObject* obj);
GType gtk_widget_example_widget_get_type (void) G_GNUC_CONST;
#define GTK_WIDGET_EXAMPLE_WIDGET_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GTK_WIDGET_EXAMPLE_TYPE_WIDGET, GtkWidgetExampleWidgetPrivate))
enum  {
	GTK_WIDGET_EXAMPLE_WIDGET_DUMMY_PROPERTY
};
GtkWidgetExampleWidget* gtk_widget_example_widget_new (void);
GtkWidgetExampleWidget* gtk_widget_example_widget_construct (GType object_type);
static void gtk_widget_example_widget_real_size_allocate (GtkWidget* base, GtkAllocation* allocation);
static GObject * gtk_widget_example_widget_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static gboolean _gtk_widget_example_widget___lambda2_ (GtkWidgetExampleWidget* self, cairo_t* cr);
static gboolean __gtk_widget_example_widget___lambda2__gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self);
static void _gtk_widget_example_widget___lambda3_ (GtkWidgetExampleWidget* self, GtkButton* ev);
static void __gtk_widget_example_widget___lambda3__gtk_button_clicked (GtkButton* _sender, gpointer self);
static gboolean _gtk_widget_example_widget___lambda4_ (GtkWidgetExampleWidget* self, cairo_t* cr);
static gboolean __gtk_widget_example_widget___lambda4__gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self);
static void _gtk_widget_example_widget___lambda5_ (GtkWidgetExampleWidget* self, GtkButton* ev);
static void __gtk_widget_example_widget___lambda5__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void gtk_widget_example_widget_finalize (GObject* obj);


GtkWidgetExampleWidgetBase* gtk_widget_example_widget_base_construct (GType object_type) {
	GtkWidgetExampleWidgetBase * self = NULL;
#line 31 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) g_object_new (object_type, NULL);
#line 29 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return self;
#line 150 "gtkwidgetexample.c"
}


GtkWidgetExampleWidgetBase* gtk_widget_example_widget_base_new (void) {
#line 29 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return gtk_widget_example_widget_base_construct (GTK_WIDGET_EXAMPLE_TYPE_WIDGET_BASE);
#line 157 "gtkwidgetexample.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 67 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return self ? g_object_ref (self) : NULL;
#line 164 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_base_real_size_allocate (GtkWidget* base, GtkAllocation* allocation) {
	GtkWidgetExampleWidgetBase * self;
	GtkAllocation _tmp0_;
	GdkWindow* _tmp1_ = NULL;
	GdkWindow* _tmp2_;
	GdkWindow* window;
	GdkWindow* _tmp3_;
	GdkWindow* _tmp4_;
	GtkAllocation _tmp5_;
	gint _tmp6_;
	GtkAllocation _tmp7_;
	gint _tmp8_;
	GtkAllocation _tmp9_;
	gint _tmp10_;
	GtkAllocation _tmp11_;
	gint _tmp12_;
#line 64 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 64 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_if_fail (allocation != NULL);
#line 65 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = *allocation;
#line 65 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_set_allocation ((GtkWidget*) self, &_tmp0_);
#line 67 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp1_ = gtk_widget_get_window ((GtkWidget*) self);
#line 67 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 67 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	window = _tmp2_;
#line 68 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp3_ = window;
#line 68 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (_tmp3_ == NULL) {
#line 69 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_g_object_unref0 (window);
#line 69 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		return;
#line 206 "gtkwidgetexample.c"
	}
#line 72 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp4_ = window;
#line 72 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp5_ = *allocation;
#line 72 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp6_ = _tmp5_.x;
#line 72 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp7_ = *allocation;
#line 72 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp8_ = _tmp7_.y;
#line 72 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp9_ = *allocation;
#line 72 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp10_ = _tmp9_.width;
#line 72 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp11_ = *allocation;
#line 72 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp12_ = _tmp11_.height;
#line 72 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gdk_window_move_resize (_tmp4_, _tmp6_, _tmp8_, _tmp10_, _tmp12_);
#line 64 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (window);
#line 230 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_base_real_realize (GtkWidget* base) {
	GtkWidgetExampleWidgetBase * self;
	GdkWindow* _tmp0_ = NULL;
	GdkWindow* _tmp1_;
	GdkWindow* window;
	GdkWindow* _tmp2_;
#line 76 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 77 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_set_realized ((GtkWidget*) self, TRUE);
#line 78 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = gtk_widget_get_window ((GtkWidget*) self);
#line 78 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 78 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	window = _tmp1_;
#line 79 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp2_ = window;
#line 79 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (_tmp2_ == NULL) {
#line 254 "gtkwidgetexample.c"
		GtkAllocation allocation = {0};
		GtkAllocation _tmp3_ = {0};
		GdkWindowAttr attributes = {0};
		GtkAllocation _tmp4_;
		gint _tmp5_;
		GtkAllocation _tmp6_;
		gint _tmp7_;
		GtkAllocation _tmp8_;
		gint _tmp9_;
		GtkAllocation _tmp10_;
		gint _tmp11_;
		gint _tmp12_ = 0;
		GdkWindow* _tmp13_ = NULL;
		GdkWindowAttr _tmp14_;
		GdkWindow* _tmp15_;
		GdkWindow* _tmp16_;
		GdkWindow* _tmp17_;
		GdkWindow* _tmp18_;
#line 81 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		gtk_widget_get_allocation ((GtkWidget*) self, &_tmp3_);
#line 81 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		allocation = _tmp3_;
#line 83 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		memset (&attributes, 0, sizeof (GdkWindowAttr));
#line 84 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp4_ = allocation;
#line 84 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp5_ = _tmp4_.x;
#line 84 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		attributes.x = _tmp5_;
#line 85 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp6_ = allocation;
#line 85 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp7_ = _tmp6_.y;
#line 85 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		attributes.y = _tmp7_;
#line 86 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp8_ = allocation;
#line 86 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp9_ = _tmp8_.width;
#line 86 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		attributes.width = _tmp9_;
#line 87 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp10_ = allocation;
#line 87 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp11_ = _tmp10_.height;
#line 87 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		attributes.height = _tmp11_;
#line 89 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp12_ = gtk_widget_get_events ((GtkWidget*) self);
#line 89 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		attributes.event_mask = _tmp12_;
#line 90 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		attributes.window_type = GDK_WINDOW_CHILD;
#line 91 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		attributes.wclass = GDK_INPUT_OUTPUT;
#line 93 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp13_ = gtk_widget_get_parent_window ((GtkWidget*) self);
#line 93 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp14_ = attributes;
#line 93 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp15_ = gdk_window_new (_tmp13_, &_tmp14_, GDK_WA_X | GDK_WA_Y);
#line 93 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_g_object_unref0 (window);
#line 93 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		window = _tmp15_;
#line 96 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp16_ = window;
#line 96 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		gdk_window_set_user_data (_tmp16_, (GObject*) self);
#line 97 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp17_ = window;
#line 97 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp18_ = _g_object_ref0 (_tmp17_);
#line 97 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		gtk_widget_set_window ((GtkWidget*) self, _tmp18_);
#line 331 "gtkwidgetexample.c"
	}
#line 76 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (window);
#line 335 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_base_real_unrealize (GtkWidget* base) {
	GtkWidgetExampleWidgetBase * self;
#line 102 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 103 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (gtk_widget_example_widget_base_parent_class)->unrealize (GTK_WIDGET (self));
#line 345 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_base_real_get_preferred_width (GtkWidget* base, gint* minimum_width, gint* natural_width) {
	GtkWidgetExampleWidgetBase * self;
	gint _vala_minimum_width = 0;
	gint _vala_natural_width = 0;
#line 106 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 108 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_vala_minimum_width = 300;
#line 109 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_vala_natural_width = 400;
#line 106 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (minimum_width) {
#line 106 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		*minimum_width = _vala_minimum_width;
#line 363 "gtkwidgetexample.c"
	}
#line 106 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (natural_width) {
#line 106 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		*natural_width = _vala_natural_width;
#line 369 "gtkwidgetexample.c"
	}
}


static void gtk_widget_example_widget_base_real_get_preferred_width_for_height (GtkWidget* base, gint height, gint* minimum_width, gint* natural_width) {
	GtkWidgetExampleWidgetBase * self;
	gint _vala_minimum_width = 0;
	gint _vala_natural_width = 0;
#line 112 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 114 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_vala_minimum_width = 300;
#line 115 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_vala_natural_width = 400;
#line 112 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (minimum_width) {
#line 112 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		*minimum_width = _vala_minimum_width;
#line 388 "gtkwidgetexample.c"
	}
#line 112 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (natural_width) {
#line 112 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		*natural_width = _vala_natural_width;
#line 394 "gtkwidgetexample.c"
	}
}


static void gtk_widget_example_widget_base_real_get_preferred_height (GtkWidget* base, gint* minimum_height, gint* natural_height) {
	GtkWidgetExampleWidgetBase * self;
	gint _vala_minimum_height = 0;
	gint _vala_natural_height = 0;
#line 118 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 120 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_vala_minimum_height = 80;
#line 121 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_vala_natural_height = 100;
#line 118 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (minimum_height) {
#line 118 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		*minimum_height = _vala_minimum_height;
#line 413 "gtkwidgetexample.c"
	}
#line 118 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (natural_height) {
#line 118 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		*natural_height = _vala_natural_height;
#line 419 "gtkwidgetexample.c"
	}
}


static void gtk_widget_example_widget_base_real_get_preferred_height_for_width (GtkWidget* base, gint width, gint* minimum_height, gint* natural_height) {
	GtkWidgetExampleWidgetBase * self;
	gint _vala_minimum_height = 0;
	gint _vala_natural_height = 0;
#line 124 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 126 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_vala_minimum_height = 80;
#line 127 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_vala_natural_height = 100;
#line 124 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (minimum_height) {
#line 124 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		*minimum_height = _vala_minimum_height;
#line 438 "gtkwidgetexample.c"
	}
#line 124 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (natural_height) {
#line 124 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		*natural_height = _vala_natural_height;
#line 444 "gtkwidgetexample.c"
	}
}


static gboolean gtk_widget_example_widget_base_real_draw (GtkWidget* base, cairo_t* cr) {
	GtkWidgetExampleWidgetBase * self;
	gboolean result = FALSE;
	GtkStyleContext* _tmp0_ = NULL;
	GtkStyleContext* _tmp1_;
	GtkStyleContext* context;
	GtkWidget* _tmp2_ = NULL;
	GtkWidget* _tmp3_;
	GtkWidget* parent;
	GtkStyleContext* _tmp4_ = NULL;
	GtkStyleContext* _tmp5_;
	GtkStyleContext* parent_context;
	gint _tmp6_;
	gint _tmp7_;
	gint x0;
	gint _tmp8_ = 0;
	gint width;
	gint _tmp9_ = 0;
	gint height;
	GtkStateFlags _tmp10_ = 0;
	GdkRGBA _tmp11_ = {0};
	GdkRGBA fg_rgba;
	GtkStateFlags _tmp12_ = 0;
	GdkRGBA _tmp13_ = {0};
	GdkRGBA parent_bg_rgba;
	cairo_t* _tmp14_;
	GdkRGBA _tmp15_;
	gdouble _tmp16_;
	GdkRGBA _tmp17_;
	gdouble _tmp18_;
	GdkRGBA _tmp19_;
	gdouble _tmp20_;
	GdkRGBA _tmp21_;
	gdouble _tmp22_;
	cairo_t* _tmp23_;
	cairo_t* _tmp24_;
	cairo_t* _tmp25_;
	cairo_t* _tmp26_;
	gint _tmp27_;
	gint _tmp28_;
	gint _tmp29_;
	gint _tmp30_;
	cairo_t* _tmp31_;
	cairo_t* _tmp32_;
	cairo_t* _tmp33_;
	cairo_t* _tmp34_;
	cairo_t* _tmp35_;
	GdkRGBA _tmp36_;
	gdouble _tmp37_;
	GdkRGBA _tmp38_;
	gdouble _tmp39_;
	GdkRGBA _tmp40_;
	gdouble _tmp41_;
	GdkRGBA _tmp42_;
	gdouble _tmp43_;
	GDateTime* _tmp44_;
	gchar* _tmp45_ = NULL;
	gchar* text;
	PangoLayout* _tmp46_;
	gint _tmp47_;
	gint _tmp48_;
	gint fontw = 0;
	gint fonth = 0;
	PangoLayout* _tmp49_;
	gint _tmp50_ = 0;
	gint _tmp51_ = 0;
	cairo_t* _tmp52_;
	cairo_t* _tmp53_;
	PangoLayout* _tmp54_;
	cairo_t* _tmp55_;
	PangoLayout* _tmp56_;
#line 130 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 130 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_val_if_fail (cr != NULL, FALSE);
#line 131 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 131 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 131 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	context = _tmp1_;
#line 133 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp2_ = gtk_widget_get_parent ((GtkWidget*) self);
#line 133 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 133 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	parent = _tmp3_;
#line 134 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp4_ = gtk_widget_get_style_context (parent);
#line 134 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 134 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	parent_context = _tmp5_;
#line 137 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp6_ = self->priv->pos;
#line 137 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp7_ = self->priv->step;
#line 137 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	x0 = _tmp6_ * _tmp7_;
#line 138 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp8_ = gtk_widget_get_allocated_width ((GtkWidget*) self);
#line 138 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	width = _tmp8_;
#line 139 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp9_ = gtk_widget_get_allocated_height ((GtkWidget*) self);
#line 139 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	height = _tmp9_;
#line 142 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp10_ = gtk_widget_get_state_flags ((GtkWidget*) self);
#line 142 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_style_context_get_color (context, _tmp10_, &_tmp11_);
#line 142 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	fg_rgba = _tmp11_;
#line 144 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp12_ = gtk_widget_get_state_flags ((GtkWidget*) self);
#line 144 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_style_context_get_background_color (parent_context, _tmp12_, &_tmp13_);
#line 144 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	parent_bg_rgba = _tmp13_;
#line 146 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp14_ = cr;
#line 146 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp15_ = parent_bg_rgba;
#line 146 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp16_ = _tmp15_.red;
#line 146 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp17_ = parent_bg_rgba;
#line 146 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp18_ = _tmp17_.green;
#line 146 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp19_ = parent_bg_rgba;
#line 146 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp20_ = _tmp19_.blue;
#line 146 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp21_ = parent_bg_rgba;
#line 146 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp22_ = _tmp21_.alpha;
#line 146 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	cairo_set_source_rgba (_tmp14_, _tmp16_, _tmp18_, _tmp20_, _tmp22_);
#line 150 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp23_ = cr;
#line 150 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	cairo_paint (_tmp23_);
#line 153 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp24_ = cr;
#line 153 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_render_background (context, _tmp24_, (gdouble) 0, (gdouble) 0, (gdouble) width, (gdouble) height);
#line 154 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp25_ = cr;
#line 154 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_render_frame (context, _tmp25_, (gdouble) 0, (gdouble) 0, (gdouble) width, (gdouble) height);
#line 157 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp26_ = cr;
#line 157 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp27_ = self->priv->margin_size;
#line 157 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp28_ = self->priv->margin_size;
#line 157 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp29_ = self->priv->margin_size;
#line 157 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp30_ = self->priv->margin_size;
#line 157 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	cairo_rectangle (_tmp26_, (gdouble) _tmp27_, (gdouble) _tmp28_, (gdouble) (width - (2 * _tmp29_)), (gdouble) (height - (2 * _tmp30_)));
#line 160 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp31_ = cr;
#line 160 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	cairo_clip (_tmp31_);
#line 163 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp32_ = cr;
#line 163 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	cairo_rectangle (_tmp32_, (gdouble) (x0 + 20), (gdouble) 20, (gdouble) (width - (2 * 20)), (gdouble) (height - (2 * 20)));
#line 166 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp33_ = cr;
#line 166 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	cairo_set_line_width (_tmp33_, 5.0);
#line 167 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp34_ = cr;
#line 167 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	cairo_stroke (_tmp34_);
#line 169 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp35_ = cr;
#line 169 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp36_ = fg_rgba;
#line 169 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp37_ = _tmp36_.red;
#line 169 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp38_ = fg_rgba;
#line 169 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp39_ = _tmp38_.green;
#line 169 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp40_ = fg_rgba;
#line 169 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp41_ = _tmp40_.blue;
#line 169 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp42_ = fg_rgba;
#line 169 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp43_ = _tmp42_.alpha;
#line 169 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	cairo_set_source_rgba (_tmp35_, _tmp37_, _tmp39_, _tmp41_, _tmp43_);
#line 171 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp44_ = self->priv->today;
#line 171 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp45_ = g_date_time_format (_tmp44_, "%b %d %S");
#line 171 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	text = _tmp45_;
#line 172 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp46_ = self->priv->layout;
#line 172 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp47_ = strlen (text);
#line 172 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp48_ = _tmp47_;
#line 172 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	pango_layout_set_text (_tmp46_, text, _tmp48_);
#line 173 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp49_ = self->priv->layout;
#line 173 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	pango_layout_get_pixel_size (_tmp49_, &_tmp50_, &_tmp51_);
#line 173 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	fontw = _tmp50_;
#line 173 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	fonth = _tmp51_;
#line 174 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp52_ = cr;
#line 174 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	cairo_move_to (_tmp52_, (gdouble) (x0 + ((width - fontw) / 2)), (gdouble) ((height - fonth) / 2));
#line 175 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp53_ = cr;
#line 175 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp54_ = self->priv->layout;
#line 175 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	pango_cairo_update_layout (_tmp53_, _tmp54_);
#line 176 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp55_ = cr;
#line 176 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp56_ = self->priv->layout;
#line 176 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	pango_cairo_show_layout (_tmp55_, _tmp56_);
#line 178 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	result = TRUE;
#line 178 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_free0 (text);
#line 178 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (parent_context);
#line 178 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (parent);
#line 178 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (context);
#line 178 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return result;
#line 698 "gtkwidgetexample.c"
}


static gboolean gtk_widget_example_widget_base_real_button_press_event (GtkWidget* base, GdkEventButton* event) {
	GtkWidgetExampleWidgetBase * self;
	gboolean result = FALSE;
#line 181 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 181 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 182 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	result = FALSE;
#line 182 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return result;
#line 713 "gtkwidgetexample.c"
}


static gboolean gtk_widget_example_widget_base_real_button_release_event (GtkWidget* base, GdkEventButton* event) {
	GtkWidgetExampleWidgetBase * self;
	gboolean result = FALSE;
	gboolean _tmp0_;
#line 185 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 185 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 186 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = self->priv->dragging;
#line 186 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (_tmp0_) {
#line 187 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		self->priv->dragging = FALSE;
#line 188 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		gtk_widget_example_widget_base_emit_changed_signal (self);
#line 733 "gtkwidgetexample.c"
	}
#line 190 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	result = FALSE;
#line 190 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return result;
#line 739 "gtkwidgetexample.c"
}


static gboolean gtk_widget_example_widget_base_real_motion_notify_event (GtkWidget* base, GdkEventMotion* event) {
	GtkWidgetExampleWidgetBase * self;
	gboolean result = FALSE;
	gboolean _tmp0_;
#line 193 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidgetBase*) base;
#line 193 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 194 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = self->priv->dragging;
#line 194 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (_tmp0_) {
#line 195 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		gtk_widget_example_widget_base_emit_changed_signal (self);
#line 757 "gtkwidgetexample.c"
	}
#line 197 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	result = FALSE;
#line 197 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return result;
#line 763 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_base_emit_changed_signal (GtkWidgetExampleWidgetBase* self) {
#line 200 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_if_fail (self != NULL);
#line 201 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_example_widget_base_redraw_canvas (self);
#line 202 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_signal_emit_by_name (self, "changed");
#line 774 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_base_redraw_canvas (GtkWidgetExampleWidgetBase* self) {
	GdkWindow* _tmp0_ = NULL;
	GdkWindow* _tmp1_;
	GdkWindow* window;
	GdkWindow* _tmp2_;
	GdkWindow* _tmp3_;
	cairo_region_t* _tmp4_ = NULL;
	cairo_region_t* region;
	GdkWindow* _tmp5_;
	cairo_region_t* _tmp6_;
	GdkWindow* _tmp7_;
#line 205 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_if_fail (self != NULL);
#line 206 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = gtk_widget_get_window ((GtkWidget*) self);
#line 206 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 206 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	window = _tmp1_;
#line 207 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp2_ = window;
#line 207 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (_tmp2_ == NULL) {
#line 208 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_g_object_unref0 (window);
#line 208 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		return;
#line 805 "gtkwidgetexample.c"
	}
#line 211 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp3_ = window;
#line 211 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp4_ = gdk_window_get_clip_region (_tmp3_);
#line 211 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	region = _tmp4_;
#line 213 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp5_ = window;
#line 213 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp6_ = region;
#line 213 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gdk_window_invalidate_region (_tmp5_, _tmp6_, TRUE);
#line 214 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp7_ = window;
#line 214 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gdk_window_process_updates (_tmp7_, TRUE);
#line 205 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_cairo_region_destroy0 (region);
#line 205 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (window);
#line 827 "gtkwidgetexample.c"
}


void gtk_widget_example_widget_base_scroll_left (GtkWidgetExampleWidgetBase* self) {
	gint _tmp0_;
#line 217 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_if_fail (self != NULL);
#line 218 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = self->priv->step;
#line 218 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_example_widget_base_scroll (self, _tmp0_);
#line 839 "gtkwidgetexample.c"
}


void gtk_widget_example_widget_base_scroll_right (GtkWidgetExampleWidgetBase* self) {
	gint _tmp0_;
#line 221 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_if_fail (self != NULL);
#line 222 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = self->priv->step;
#line 222 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_example_widget_base_scroll (self, -_tmp0_);
#line 851 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_base_scroll (GtkWidgetExampleWidgetBase* self, gint step) {
	gint _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	GdkWindow* _tmp3_ = NULL;
	GdkWindow* _tmp4_;
	GdkWindow* window;
	GdkWindow* _tmp5_;
	cairo_region_t* _tmp6_ = NULL;
	cairo_region_t* region;
	GdkWindow* _tmp7_;
	cairo_region_t* _tmp8_;
	gint _tmp9_;
	GdkRectangle rect = {0};
	gint x1 = 0;
	gint x2 = 0;
	gint _tmp10_;
	gint _tmp18_;
	gint _tmp19_ = 0;
	GdkWindow* _tmp20_;
	GdkRectangle _tmp21_;
	gint _tmp22_;
	gint _tmp23_;
	GdkWindow* _tmp24_;
	GdkRectangle _tmp25_;
#line 225 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_if_fail (self != NULL);
#line 226 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = self->priv->pos;
#line 226 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp1_ = step;
#line 226 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp2_ = self->priv->step;
#line 226 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->pos = _tmp0_ + (_tmp1_ / _tmp2_);
#line 228 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp3_ = gtk_widget_get_window ((GtkWidget*) self);
#line 228 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp4_ = _g_object_ref0 (_tmp3_);
#line 228 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	window = _tmp4_;
#line 229 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp5_ = window;
#line 229 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp6_ = gdk_window_get_visible_region (_tmp5_);
#line 229 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	region = _tmp6_;
#line 230 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp7_ = window;
#line 230 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp8_ = region;
#line 230 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp9_ = step;
#line 230 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gdk_window_move_region (_tmp7_, _tmp8_, _tmp9_, 0);
#line 232 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	memset (&rect, 0, sizeof (GdkRectangle));
#line 234 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp10_ = step;
#line 234 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (_tmp10_ > 0) {
#line 916 "gtkwidgetexample.c"
		gint _tmp11_ = 0;
		gint _tmp12_;
		gint _tmp13_;
#line 235 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		x1 = 0;
#line 236 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp11_ = gtk_widget_get_allocated_width ((GtkWidget*) self);
#line 236 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp12_ = self->priv->margin_size;
#line 236 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		x2 = _tmp11_ - _tmp12_;
#line 237 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp13_ = step;
#line 237 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		rect.width = _tmp13_ * 2;
#line 932 "gtkwidgetexample.c"
	} else {
		gint _tmp14_ = 0;
		gint _tmp15_;
		gdouble _tmp16_ = 0.0;
		gint _tmp17_;
#line 239 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp14_ = gtk_widget_get_allocated_width ((GtkWidget*) self);
#line 239 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp15_ = step;
#line 239 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp16_ = fabs (_tmp15_ * 2.0);
#line 239 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		x1 = _tmp14_ - ((gint) _tmp16_);
#line 240 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		x2 = 0;
#line 241 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp17_ = step;
#line 241 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		rect.width = (-_tmp17_) * 2;
#line 952 "gtkwidgetexample.c"
	}
#line 243 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp18_ = x1;
#line 243 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	rect.x = _tmp18_;
#line 244 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	rect.y = 0;
#line 245 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp19_ = gtk_widget_get_allocated_height ((GtkWidget*) self);
#line 245 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	rect.height = _tmp19_;
#line 246 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp20_ = window;
#line 246 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp21_ = rect;
#line 246 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gdk_window_invalidate_rect (_tmp20_, &_tmp21_, FALSE);
#line 247 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp22_ = x2;
#line 247 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	rect.x = _tmp22_;
#line 248 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp23_ = self->priv->margin_size;
#line 248 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	rect.width = _tmp23_;
#line 249 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp24_ = window;
#line 249 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp25_ = rect;
#line 249 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gdk_window_invalidate_rect (_tmp24_, &_tmp25_, FALSE);
#line 225 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_cairo_region_destroy0 (region);
#line 225 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (window);
#line 988 "gtkwidgetexample.c"
}


static GObject * gtk_widget_example_widget_base_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	GtkWidgetExampleWidgetBase * self;
	GtkCssProvider* _tmp0_;
	GtkStyleContext* _tmp2_ = NULL;
	GtkStyleContext* _tmp3_;
	GtkStyleContext* style_context;
	GtkStyleContext* _tmp4_;
	GtkCssProvider* _tmp5_;
	GtkStyleContext* _tmp6_;
	GtkStyleContext* _tmp7_;
	GtkStyleContext* _tmp8_;
	GtkStateFlags _tmp9_ = 0;
	GtkBorder _tmp10_ = {0};
	GtkBorder margin;
	GtkStyleContext* _tmp11_;
	GtkStateFlags _tmp12_ = 0;
	GtkBorder _tmp13_ = {0};
	GtkBorder border;
	GtkBorder _tmp14_;
	gint16 _tmp15_;
	GtkBorder _tmp16_;
	gint16 _tmp17_;
	PangoLayout* _tmp18_ = NULL;
	GDateTime* _tmp19_;
	GError * _inner_error_ = NULL;
#line 34 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	parent_class = G_OBJECT_CLASS (gtk_widget_example_widget_base_parent_class);
#line 34 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 34 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = GTK_WIDGET_EXAMPLE_WIDGET_BASE (obj);
#line 36 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_add_events ((GtkWidget*) self, (gint) (((GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK) | GDK_POINTER_MOTION_MASK) | GDK_EXPOSURE_MASK));
#line 42 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_set_has_window ((GtkWidget*) self, TRUE);
#line 43 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = gtk_css_provider_new ();
#line 43 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (self->priv->css_provider);
#line 43 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->css_provider = _tmp0_;
#line 1035 "gtkwidgetexample.c"
	{
		GtkCssProvider* _tmp1_;
#line 45 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_tmp1_ = self->priv->css_provider;
#line 45 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		gtk_css_provider_load_from_path (_tmp1_, "./gtkwidgetexample.css", &_inner_error_);
#line 45 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		if (_inner_error_ != NULL) {
#line 1044 "gtkwidgetexample.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
#line 44 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		e = _inner_error_;
#line 44 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_inner_error_ = NULL;
#line 44 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		_g_error_free0 (e);
#line 1058 "gtkwidgetexample.c"
	}
	__finally0:
#line 44 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	if (_inner_error_ != NULL) {
#line 44 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 44 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
		g_clear_error (&_inner_error_);
#line 1067 "gtkwidgetexample.c"
	}
#line 50 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 50 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 50 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	style_context = _tmp3_;
#line 51 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp4_ = style_context;
#line 51 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp5_ = self->priv->css_provider;
#line 51 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_style_context_add_provider (_tmp4_, (GtkStyleProvider*) _tmp5_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 53 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp6_ = style_context;
#line 53 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_style_context_add_class (_tmp6_, "widgetexample");
#line 54 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp7_ = style_context;
#line 54 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_style_context_add_class (_tmp7_, GTK_STYLE_CLASS_ENTRY);
#line 56 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp8_ = style_context;
#line 56 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp9_ = gtk_widget_get_state_flags ((GtkWidget*) self);
#line 56 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_style_context_get_margin (_tmp8_, _tmp9_, &_tmp10_);
#line 56 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	margin = _tmp10_;
#line 57 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp11_ = style_context;
#line 57 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp12_ = gtk_widget_get_state_flags ((GtkWidget*) self);
#line 57 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_style_context_get_border (_tmp11_, _tmp12_, &_tmp13_);
#line 57 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	border = _tmp13_;
#line 59 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp14_ = margin;
#line 59 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp15_ = _tmp14_.left;
#line 59 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp16_ = border;
#line 59 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp17_ = _tmp16_.left;
#line 59 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->margin_size = (_tmp15_ + _tmp17_) + 2;
#line 60 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp18_ = gtk_widget_create_pango_layout ((GtkWidget*) self, NULL);
#line 60 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (self->priv->layout);
#line 60 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->layout = _tmp18_;
#line 61 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp19_ = g_date_time_new_now_local ();
#line 61 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_date_time_unref0 (self->priv->today);
#line 61 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->today = _tmp19_;
#line 34 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (style_context);
#line 34 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return obj;
#line 1131 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_base_class_init (GtkWidgetExampleWidgetBaseClass * klass) {
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_example_widget_base_parent_class = g_type_class_peek_parent (klass);
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_type_class_add_private (klass, sizeof (GtkWidgetExampleWidgetBasePrivate));
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->size_allocate = gtk_widget_example_widget_base_real_size_allocate;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->realize = gtk_widget_example_widget_base_real_realize;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->unrealize = gtk_widget_example_widget_base_real_unrealize;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->get_preferred_width = gtk_widget_example_widget_base_real_get_preferred_width;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->get_preferred_width_for_height = gtk_widget_example_widget_base_real_get_preferred_width_for_height;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->get_preferred_height = gtk_widget_example_widget_base_real_get_preferred_height;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->get_preferred_height_for_width = gtk_widget_example_widget_base_real_get_preferred_height_for_width;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->draw = gtk_widget_example_widget_base_real_draw;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->button_press_event = gtk_widget_example_widget_base_real_button_press_event;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->button_release_event = gtk_widget_example_widget_base_real_button_release_event;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->motion_notify_event = gtk_widget_example_widget_base_real_motion_notify_event;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	G_OBJECT_CLASS (klass)->constructor = gtk_widget_example_widget_base_constructor;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	G_OBJECT_CLASS (klass)->finalize = gtk_widget_example_widget_base_finalize;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_signal_new ("changed", GTK_WIDGET_EXAMPLE_TYPE_WIDGET_BASE, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 1168 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_base_instance_init (GtkWidgetExampleWidgetBase * self) {
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv = GTK_WIDGET_EXAMPLE_WIDGET_BASE_GET_PRIVATE (self);
#line 22 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->step = 10;
#line 23 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->pos = 0;
#line 1179 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_base_finalize (GObject* obj) {
	GtkWidgetExampleWidgetBase * self;
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = GTK_WIDGET_EXAMPLE_WIDGET_BASE (obj);
#line 20 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (self->priv->css_provider);
#line 21 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (self->priv->layout);
#line 25 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_date_time_unref0 (self->priv->today);
#line 17 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	G_OBJECT_CLASS (gtk_widget_example_widget_base_parent_class)->finalize (obj);
#line 1195 "gtkwidgetexample.c"
}


GType gtk_widget_example_widget_base_get_type (void) {
	static volatile gsize gtk_widget_example_widget_base_type_id__volatile = 0;
	if (g_once_init_enter (&gtk_widget_example_widget_base_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GtkWidgetExampleWidgetBaseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtk_widget_example_widget_base_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkWidgetExampleWidgetBase), 0, (GInstanceInitFunc) gtk_widget_example_widget_base_instance_init, NULL };
		GType gtk_widget_example_widget_base_type_id;
		gtk_widget_example_widget_base_type_id = g_type_register_static (GTK_TYPE_WIDGET, "GtkWidgetExampleWidgetBase", &g_define_type_info, 0);
		g_once_init_leave (&gtk_widget_example_widget_base_type_id__volatile, gtk_widget_example_widget_base_type_id);
	}
	return gtk_widget_example_widget_base_type_id__volatile;
}


GtkWidgetExampleWidget* gtk_widget_example_widget_construct (GType object_type) {
	GtkWidgetExampleWidget * self = NULL;
#line 263 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidget*) g_object_new (object_type, NULL);
#line 261 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return self;
#line 1217 "gtkwidgetexample.c"
}


GtkWidgetExampleWidget* gtk_widget_example_widget_new (void) {
#line 261 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return gtk_widget_example_widget_construct (GTK_WIDGET_EXAMPLE_TYPE_WIDGET);
#line 1224 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_real_size_allocate (GtkWidget* base, GtkAllocation* allocation) {
	GtkWidgetExampleWidget * self;
	GtkAllocation _tmp0_;
	GtkAllocation _tmp1_;
	gint _tmp2_;
	GtkAllocation _tmp3_;
	gint _tmp4_;
#line 317 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = (GtkWidgetExampleWidget*) base;
#line 317 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_if_fail (allocation != NULL);
#line 318 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = *allocation;
#line 318 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (gtk_widget_example_widget_parent_class)->size_allocate ((GtkWidget*) GTK_GRID (self), &_tmp0_);
#line 320 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp1_ = *allocation;
#line 320 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp2_ = _tmp1_.width;
#line 320 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->width = _tmp2_;
#line 321 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp3_ = *allocation;
#line 321 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp4_ = _tmp3_.height;
#line 321 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->height = _tmp4_;
#line 1255 "gtkwidgetexample.c"
}


static gboolean _gtk_widget_example_widget___lambda2_ (GtkWidgetExampleWidget* self, cairo_t* cr) {
	gboolean result = FALSE;
	GtkButton* _tmp0_;
	gint _tmp1_ = 0;
	gint width;
	GtkButton* _tmp2_;
	gint _tmp3_ = 0;
	gint height;
	gint size;
	GtkButton* _tmp4_;
	GtkStyleContext* _tmp5_ = NULL;
	GtkStyleContext* _tmp6_;
	GtkStyleContext* context;
	GtkStyleContext* _tmp7_;
	cairo_t* _tmp8_;
	gint _tmp9_;
	gint _tmp10_;
	gint _tmp11_;
	gint _tmp12_;
	gint _tmp13_;
#line 284 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_val_if_fail (cr != NULL, FALSE);
#line 285 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = self->priv->lbutton;
#line 285 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp1_ = gtk_widget_get_allocated_width ((GtkWidget*) _tmp0_);
#line 285 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	width = _tmp1_;
#line 286 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp2_ = self->priv->lbutton;
#line 286 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp3_ = gtk_widget_get_allocated_height ((GtkWidget*) _tmp2_);
#line 286 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	height = _tmp3_;
#line 287 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	size = 8;
#line 288 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp4_ = self->priv->lbutton;
#line 288 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
#line 288 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp6_ = _g_object_ref0 (_tmp5_);
#line 288 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	context = _tmp6_;
#line 289 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp7_ = context;
#line 289 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp8_ = cr;
#line 289 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp9_ = width;
#line 289 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp10_ = size;
#line 289 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp11_ = height;
#line 289 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp12_ = size;
#line 289 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp13_ = size;
#line 289 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_render_arrow (_tmp7_, _tmp8_, 3 * G_PI_2, (gdouble) ((_tmp9_ / 2) - (_tmp10_ / 2)), (gdouble) ((_tmp11_ / 2) - (_tmp12_ / 2)), (gdouble) _tmp13_);
#line 292 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	result = FALSE;
#line 292 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (context);
#line 292 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return result;
#line 1325 "gtkwidgetexample.c"
}


static gboolean __gtk_widget_example_widget___lambda2__gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self) {
	gboolean result;
	result = _gtk_widget_example_widget___lambda2_ (self, cr);
#line 284 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return result;
#line 1334 "gtkwidgetexample.c"
}


static void _gtk_widget_example_widget___lambda3_ (GtkWidgetExampleWidget* self, GtkButton* ev) {
	GtkWidgetExampleWidgetBase* _tmp0_;
#line 294 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_if_fail (ev != NULL);
#line 295 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = self->priv->widget;
#line 295 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_example_widget_base_scroll_left (_tmp0_);
#line 1346 "gtkwidgetexample.c"
}


static void __gtk_widget_example_widget___lambda3__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 294 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_gtk_widget_example_widget___lambda3_ (self, _sender);
#line 1353 "gtkwidgetexample.c"
}


static gboolean _gtk_widget_example_widget___lambda4_ (GtkWidgetExampleWidget* self, cairo_t* cr) {
	gboolean result = FALSE;
	GtkButton* _tmp0_;
	gint _tmp1_ = 0;
	gint width;
	GtkButton* _tmp2_;
	gint _tmp3_ = 0;
	gint height;
	gint size;
	GtkButton* _tmp4_;
	GtkStyleContext* _tmp5_ = NULL;
	GtkStyleContext* _tmp6_;
	GtkStyleContext* context;
	GtkStyleContext* _tmp7_;
	cairo_t* _tmp8_;
	gint _tmp9_;
	gint _tmp10_;
	gint _tmp11_;
	gint _tmp12_;
	gint _tmp13_;
#line 300 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_val_if_fail (cr != NULL, FALSE);
#line 301 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = self->priv->rbutton;
#line 301 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp1_ = gtk_widget_get_allocated_width ((GtkWidget*) _tmp0_);
#line 301 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	width = _tmp1_;
#line 302 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp2_ = self->priv->rbutton;
#line 302 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp3_ = gtk_widget_get_allocated_height ((GtkWidget*) _tmp2_);
#line 302 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	height = _tmp3_;
#line 303 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	size = 8;
#line 304 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp4_ = self->priv->lbutton;
#line 304 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
#line 304 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp6_ = _g_object_ref0 (_tmp5_);
#line 304 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	context = _tmp6_;
#line 305 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp7_ = context;
#line 305 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp8_ = cr;
#line 305 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp9_ = width;
#line 305 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp10_ = size;
#line 305 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp11_ = height;
#line 305 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp12_ = size;
#line 305 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp13_ = size;
#line 305 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_render_arrow (_tmp7_, _tmp8_, G_PI_2, (gdouble) ((_tmp9_ / 2) - (_tmp10_ / 2)), (gdouble) ((_tmp11_ / 2) - (_tmp12_ / 2)), (gdouble) _tmp13_);
#line 308 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	result = FALSE;
#line 308 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (context);
#line 308 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return result;
#line 1423 "gtkwidgetexample.c"
}


static gboolean __gtk_widget_example_widget___lambda4__gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self) {
	gboolean result;
	result = _gtk_widget_example_widget___lambda4_ (self, cr);
#line 300 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return result;
#line 1432 "gtkwidgetexample.c"
}


static void _gtk_widget_example_widget___lambda5_ (GtkWidgetExampleWidget* self, GtkButton* ev) {
	GtkWidgetExampleWidgetBase* _tmp0_;
#line 310 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_return_if_fail (ev != NULL);
#line 311 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = self->priv->widget;
#line 311 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_example_widget_base_scroll_right (_tmp0_);
#line 1444 "gtkwidgetexample.c"
}


static void __gtk_widget_example_widget___lambda5__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 310 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_gtk_widget_example_widget___lambda5_ (self, _sender);
#line 1451 "gtkwidgetexample.c"
}


static GObject * gtk_widget_example_widget_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	GtkWidgetExampleWidget * self;
	GtkWidgetExampleWidgetBase* _tmp0_;
	GtkWidgetExampleWidgetBase* _tmp1_;
	GtkWidgetExampleWidgetBase* _tmp2_;
	GtkWidgetExampleWidgetBase* _tmp3_;
	GtkWidgetExampleWidgetBase* _tmp4_;
	GtkButton* _tmp5_;
	GtkButton* _tmp6_;
	GtkButton* _tmp7_;
	GtkButton* _tmp8_;
	GtkButton* _tmp9_;
	GtkButton* _tmp10_;
	GtkButton* _tmp11_;
	GtkButton* _tmp12_;
	GtkButton* _tmp13_;
	GtkButton* _tmp14_;
	GtkButton* _tmp15_;
	GtkButton* _tmp16_;
	GtkButton* _tmp17_;
	GtkButton* _tmp18_;
#line 266 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	parent_class = G_OBJECT_CLASS (gtk_widget_example_widget_parent_class);
#line 266 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 266 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = GTK_WIDGET_EXAMPLE_WIDGET (obj);
#line 268 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 3);
#line 269 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, 500, 50);
#line 271 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_grid_insert_row ((GtkGrid*) self, 0);
#line 272 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_grid_insert_row ((GtkGrid*) self, 0);
#line 273 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_grid_insert_column ((GtkGrid*) self, 0);
#line 274 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_grid_insert_column ((GtkGrid*) self, 0);
#line 276 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp0_ = gtk_widget_example_widget_base_new ();
#line 276 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp1_ = g_object_ref_sink (_tmp0_);
#line 276 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (self->priv->widget);
#line 276 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->widget = _tmp1_;
#line 277 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp2_ = self->priv->widget;
#line 277 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp2_, TRUE);
#line 278 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp3_ = self->priv->widget;
#line 278 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp3_, TRUE);
#line 279 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp4_ = self->priv->widget;
#line 279 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp4_, 1, 0, 1, 1);
#line 281 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp5_ = (GtkButton*) gtk_button_new ();
#line 281 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp6_ = g_object_ref_sink (_tmp5_);
#line 281 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (self->priv->lbutton);
#line 281 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->lbutton = _tmp6_;
#line 282 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp7_ = self->priv->lbutton;
#line 282 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp7_, TRUE);
#line 283 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp8_ = self->priv->lbutton;
#line 283 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_set_size_request ((GtkWidget*) _tmp8_, 15, 50);
#line 284 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp9_ = self->priv->lbutton;
#line 284 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_signal_connect_object ((GtkWidget*) _tmp9_, "draw", (GCallback) __gtk_widget_example_widget___lambda2__gtk_widget_draw, self, G_CONNECT_AFTER);
#line 294 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp10_ = self->priv->lbutton;
#line 294 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_signal_connect_object (_tmp10_, "clicked", (GCallback) __gtk_widget_example_widget___lambda3__gtk_button_clicked, self, G_CONNECT_AFTER);
#line 297 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp11_ = (GtkButton*) gtk_button_new ();
#line 297 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp12_ = g_object_ref_sink (_tmp11_);
#line 297 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (self->priv->rbutton);
#line 297 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv->rbutton = _tmp12_;
#line 298 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp13_ = self->priv->rbutton;
#line 298 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp13_, TRUE);
#line 299 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp14_ = self->priv->rbutton;
#line 299 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_set_size_request ((GtkWidget*) _tmp14_, 15, 50);
#line 300 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp15_ = self->priv->rbutton;
#line 300 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_signal_connect_object ((GtkWidget*) _tmp15_, "draw", (GCallback) __gtk_widget_example_widget___lambda4__gtk_widget_draw, self, G_CONNECT_AFTER);
#line 310 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp16_ = self->priv->rbutton;
#line 310 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_signal_connect_object (_tmp16_, "clicked", (GCallback) __gtk_widget_example_widget___lambda5__gtk_button_clicked, self, G_CONNECT_AFTER);
#line 313 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp17_ = self->priv->lbutton;
#line 313 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp17_, 0, 0, 1, 2);
#line 314 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_tmp18_ = self->priv->rbutton;
#line 314 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp18_, 2, 0, 1, 2);
#line 266 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	return obj;
#line 1574 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_class_init (GtkWidgetExampleWidgetClass * klass) {
#line 253 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	gtk_widget_example_widget_parent_class = g_type_class_peek_parent (klass);
#line 253 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	g_type_class_add_private (klass, sizeof (GtkWidgetExampleWidgetPrivate));
#line 253 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	GTK_WIDGET_CLASS (klass)->size_allocate = gtk_widget_example_widget_real_size_allocate;
#line 253 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	G_OBJECT_CLASS (klass)->constructor = gtk_widget_example_widget_constructor;
#line 253 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	G_OBJECT_CLASS (klass)->finalize = gtk_widget_example_widget_finalize;
#line 1589 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_instance_init (GtkWidgetExampleWidget * self) {
#line 253 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self->priv = GTK_WIDGET_EXAMPLE_WIDGET_GET_PRIVATE (self);
#line 1596 "gtkwidgetexample.c"
}


static void gtk_widget_example_widget_finalize (GObject* obj) {
	GtkWidgetExampleWidget * self;
#line 253 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	self = GTK_WIDGET_EXAMPLE_WIDGET (obj);
#line 257 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (self->priv->widget);
#line 258 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (self->priv->lbutton);
#line 259 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	_g_object_unref0 (self->priv->rbutton);
#line 253 "/home/luiz/projects/GtkWidgetExampleVala/src/gtkwidgetexample.vala"
	G_OBJECT_CLASS (gtk_widget_example_widget_parent_class)->finalize (obj);
#line 1612 "gtkwidgetexample.c"
}


GType gtk_widget_example_widget_get_type (void) {
	static volatile gsize gtk_widget_example_widget_type_id__volatile = 0;
	if (g_once_init_enter (&gtk_widget_example_widget_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GtkWidgetExampleWidgetClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtk_widget_example_widget_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkWidgetExampleWidget), 0, (GInstanceInitFunc) gtk_widget_example_widget_instance_init, NULL };
		GType gtk_widget_example_widget_type_id;
		gtk_widget_example_widget_type_id = g_type_register_static (GTK_TYPE_GRID, "GtkWidgetExampleWidget", &g_define_type_info, 0);
		g_once_init_leave (&gtk_widget_example_widget_type_id__volatile, gtk_widget_example_widget_type_id);
	}
	return gtk_widget_example_widget_type_id__volatile;
}



